version: '3.8'

secrets:
  db_password:
    file: ./secrets/db_password.txt

services:
  postgres:
    image: postgres:15-alpine
    container_name: tech-challenge-db
    secrets:
      - db_password
    environment:
      POSTGRES_DB: tech_challenge_blog
      POSTGRES_USER: admin
      POSTGRES_PASSWORD_FILE: /run/secrets/db_password
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - tech-challenge-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: tech-challenge-backend
    environment:
      NODE_ENV: development
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: tech_challenge_blog
      DB_USER: admin
      DB_PASSWORD: ${DB_PASSWORD}
      JWT_SECRET_FILE: ${JWT_SECRET}
      JWT_ACCESS_EXPIRES_IN: 15m
      JWT_REFRESH_EXPIRES_IN: 86400
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      AWS_S3_BUCKET: tech-challenge-blog-vlab-helington
      AWS_REGION: sa-east-1
    ports:
      - "3001:3001"
    depends_on:
      - postgres
    volumes:
      - ./backend:/app
    networks:
      - tech-challenge-network
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "admin"]
      interval: 30s
      timeout: 10s
      retries: 3
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: tech-challenge-frontend
    environment:
      REACT_APP_API_URL: http://localhost:3001/api
    ports:
      - "3000:3000"
    depends_on:
      - backend
    volumes:
      - /app/node_modules
    networks:
      - tech-challenge-network

volumes:
  postgres_data:

networks:
  tech-challenge-network:
    driver: bridge